version: '3'

services:
  api: # Python Flask api
    container_name: secondhandsurfer-back
    build: .
    ports:
      - "5000:5000" # Expose API port


  frontend: # Nginx Server For Frontend App
    container_name: secondhandsurfer-front
    image: nginx
    volumes: # Serve local "public" dir
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80" # Forward site to localhost:8080

  elasticsearch: # Elasticsearch Instance
    container_name: secondhandsurfer-search
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    volumes: # Persist ES data in seperate "esdata" volume
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"

volumes: # Define seperate volume for Elasticsearch data
  esdata: